---
 
- name: Deploy the application to the "production" server
  hosts: production
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Create the application directory
      file:
        path: /home/ubuntu/mongo
        state: directory
        owner: ubuntu
        group: ubuntu
    - name: Copy jar file over
      copy:
        src: /var/jenkins_home/workspace/mvn-sonar/target/mongo-0.0.1-SNAPSHOT.jar
        dest: /home/ubuntu/mongo
        owner: ubuntu
        group: ubuntu
      